=== PeterBilberg/WeatherCollector/src/main/resources/cityCollectionJaxB/cityCollection.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:tn="peterBilberg.com/weather/cityCollection/schema" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="peterBilberg.com/weather/cityCollection/schema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="cityCollection">
		<xs:complexType>
			<xs:sequence>
			<xs:element name="version" type="xs:string" minOccurs="1" maxOccurs="1"/>
				<xs:element name="citylist" type="tn:citylistType" minOccurs="0" maxOccurs="1"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="citylistType">
		<xs:sequence>
			<xs:element name="city" type="tn:cityType" minOccurs="0" maxOccurs="unbounded"/>	
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cityType">
		<xs:sequence>
			<xs:element name="name" type="xs:string"/>
			<xs:element name="country" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== PeterBilberg/WeatherCollector/src/main/resources/Testinput/xmlValidation/cityCollectionForTest_NotWellFormed.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<tn:cityCollection xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tn="peterBilberg.com/weather/cityCollection/schema" xsi:schemaLocation="peterBilberg.com/weather/cityCollection/schema file:///C:/Users/pbi/Documents/NetBeansProjects/WeatherCollector/src/main/resources/cityCollectionJaxB/cityCollection.xsd">
	<tn:version>1.0.0</tn:version>
	<tn:citylist>
		<tn:cityx>
			<tn:name>Säffle</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bielefeld</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Brunswick%20%2F%20Braunschweig</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Haderslev</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Dortmund</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Herlev</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Stockholm</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Brøndby</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Esbjerg</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sölvesborg</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Hjo</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Newport</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Preston</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Glostrup</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Roskilde</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Remscheid</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Münster</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Ängelholm</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Hjørring</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Cambridge</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Karlsruhe</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bremen</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Køge</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Malmö</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Southampton</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Västervik</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Berlin</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Djursholm</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Frederikshavn</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Vadstena</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bradford</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Plymouth</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Säter</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Karlskrona</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Borås</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Falsterbo</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Augsburg</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Filipstad</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Leverkusen</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Kristinehamn</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Skara</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Durham</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sigtuna</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Halle</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Lindesberg</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Hereford</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Mainz</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bremerhaven</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Helsingør</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Vetlanda</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Glasgow</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Viborg</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Fredericia</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Herne</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Mönchengladbach</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Linköping</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Leeds</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Kungsbacka</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Oxelösund</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Torshälla</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Hanover</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Duisburg</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Trelleborg</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sunderland</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Höganäs</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Randers</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sävsjö</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Fagersta</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Borlänge</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Lübeck</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Slagelse</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Skellefteå</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Ringsted</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Söderhamn</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Eskilstuna</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Piteå</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Silkeborg</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Vänersborg</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Gentofte</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Odense</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Liverpool</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Gloucester</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Strömstad</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Hedemora</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sandviken</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Ølstykke-Stenløse</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Växjö</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Härnösand</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Sheffield</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Oberhausen</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Wakefield</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Chichester</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Gävle</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Eksjö</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Enköping</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Cambridgeshire</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Siegen</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bollnäs</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Dundee</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Södertälje</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Falkenberg</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Bonn</tn:name>
			<tn:country>de</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Halmstad</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Derby</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Horsens</tn:name>
			<tn:country>dk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Manchester</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Stirling</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Alingsås</tn:name>
			<tn:country>se</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Oxford</tn:name>
			<tn:country>uk</tn:country>
		</tn:city>
		<tn:city>
			<tn:name>Uppsala</tn:name>
